// Code generated by mockery v2.36.0. DO NOT EDIT.

package pb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUsersServiceServer is an autogenerated mock type for the UsersServiceServer type
type MockUsersServiceServer struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *MockUsersServiceServer) CreateUser(_a0 context.Context, _a1 *CreateUserRequest) (*CreateUserResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *CreateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateUserRequest) (*CreateUserResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateUserRequest) *CreateUserResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateUserRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedUsersServiceServer provides a mock function with given fields:
func (_m *MockUsersServiceServer) mustEmbedUnimplementedUsersServiceServer() {
	_m.Called()
}

// NewMockUsersServiceServer creates a new instance of MockUsersServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersServiceServer {
	mock := &MockUsersServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
