openapiOptions:
  file:
    - file: "account.proto"
      option:
        info:
          title: Magnament Users
          version: "0.0.1"
  method:
    - method: proto.AccountService.CreateUser
      option:
        operationId: createUser
        tags:
          - Account
        summary: Create a new User