openapiOptions:
  file:
    - file: "account.proto"
      option:
        info:
          title: Account Service
          version: "0.0.1"
        basePath: /api/v1/account
  method:
    - method: grpc.AccountService.CreateUser
      option:
        operationId: createUser
        tags:
          - Account
        summary: Create user